version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install

  post_build:
    commands:
      - echo Build completed on `date`
      - cp target/*.jar target/app.jar

artifacts:
  files:
    - '**/*'
